from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.sonyPs3Configuration import SonyPs3Configuration


consoleConfiguration: AbsConsoleConfiguration = SonyPs3Configuration()
applyConfiguration(consoleConfiguration)
