from applyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.gameCubeConfiguration import GameCubeConfiguration


consoleConfiguration: ConsoleConfiguration = GameCubeConfiguration()
applyConfiguration(consoleConfiguration)
