from applyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.sonyPs3Configuration import SonyPs3Configuration


consoleConfiguration: ConsoleConfiguration = SonyPs3Configuration()
applyConfiguration(consoleConfiguration)
