from charlesApplyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.superFamicomConfiguration import SuperFamicomConfiguration


consoleConfiguration: ConsoleConfiguration = SuperFamicomConfiguration()
applyConfiguration(consoleConfiguration)
