from charlesApplyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.megaSgConfiguration import MegaSgConfiguration


consoleConfiguration: ConsoleConfiguration = MegaSgConfiguration()
applyConfiguration(consoleConfiguration)
