from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.ntMiniNoirConfiguration import NtMiniNoirConfiguration


consoleConfiguration: AbsConsoleConfiguration = NtMiniNoirConfiguration()
applyConfiguration(consoleConfiguration)
