from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.sonyPs1Configuration import SonyPs1Configuration


consoleConfiguration: AbsConsoleConfiguration = SonyPs1Configuration()
applyConfiguration(consoleConfiguration)
