from applyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.nintendo64Configuration import Nintendo64Configuration


consoleConfiguration: ConsoleConfiguration = Nintendo64Configuration()
applyConfiguration(consoleConfiguration)
