from charlesApplyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.ntMiniNoirConfiguration import NtMiniNoirConfiguration


consoleConfiguration: ConsoleConfiguration = NtMiniNoirConfiguration()
applyConfiguration(consoleConfiguration)
