from applyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.sonyPs1Configuration import SonyPs1Configuration


consoleConfiguration: ConsoleConfiguration = SonyPs1Configuration()
applyConfiguration(consoleConfiguration)
