from charlesApplyConfiguration import applyConfiguration
from consoles.consoleConfiguration import ConsoleConfiguration
from consoles.segaDreamcastConfiguration import SegaDreamcastConfiguration


consoleConfiguration: ConsoleConfiguration = SegaDreamcastConfiguration()
applyConfiguration(consoleConfiguration)
