from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.gameCubeConfiguration import GameCubeConfiguration


consoleConfiguration: AbsConsoleConfiguration = GameCubeConfiguration()
applyConfiguration(consoleConfiguration)
