from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.megaSgConfiguration import MegaSgConfiguration


consoleConfiguration: AbsConsoleConfiguration = MegaSgConfiguration()
applyConfiguration(consoleConfiguration)
