from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.nintendo64Configuration import Nintendo64Configuration


consoleConfiguration: AbsConsoleConfiguration = Nintendo64Configuration()
applyConfiguration(consoleConfiguration)
