from applyConfiguration import applyConfiguration
from consoles.absConsoleConfiguration import AbsConsoleConfiguration
from consoles.superFamicomConfiguration import SuperFamicomConfiguration


consoleConfiguration: AbsConsoleConfiguration = SuperFamicomConfiguration()
applyConfiguration(consoleConfiguration)
